name = "Chocolateycraft"
author = "paperclone22"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa31b55fccfb1766778f968d6b79d0cf421f2ed30112e1c86cf03d642aed9b3f"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
