name = "Chocolateycraft"
author = "paperclone22"
version = "0.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59e72b9bce89080c9a8c05534ee0cece6a23999b9fab51a2ebd3e7a47388c938"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
