name = "Chocolateycraft"
author = "paperclone22"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ee7cba844152482fdd91ee8632d91867b954bc69f59dcba358d3924a20b0568"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
