name = "Chocolateycraft"
author = "paperclone22"
version = "0.2.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "502487cc1e1d77a84e3cffd02306bbb7011ad5e874a50f967735d59645f8d5d8"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
