name = "Chocolateycraft"
author = "paperclone22"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7c5ce6aaaf724ed5df4d300583d21b1a7b8e86e0160d61ab71d6859f7d09ac4"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
