# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fastest"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				area_effect_cloud = true
				armor_stand = true
				arrow = true
				axolotl = false
				bat = false
				bee = false
				blaze = true
				boat = false
				cat = false
				cave_spider = true
				chicken = false
				cod = false
				cow = false
				creeper = true
				dolphin = false
				donkey = false
				dragon_fireball = true
				drowned = false
				elder_guardian = false
				end_crystal = true
				ender_dragon = true
				enderman = true
				endermite = false
				evoker = true
				evoker_fangs = true
				experience_orb = true
				eye_of_ender = true
				falling_block = false
				firework_rocket = false
				fox = false
				ghast = false
				giant = false
				glow_squid = true
				goat = false
				guardian = false
				hoglin = false
				horse = false
				husk = false
				illusioner = false
				iron_golem = false
				item = true
				item_frame = false
				fireball = true
				leash_knot = false
				lightning_bolt = true
				llama = false
				llama_spit = false
				magma_cube = true
				marker = true
				minecart = false
				chest_minecart = false
				command_block_minecart = false
				furnace_minecart = true
				hopper_minecart = false
				spawner_minecart = false
				tnt_minecart = false
				mule = false
				mooshroom = false
				ocelot = false
				painting = false
				panda = false
				parrot = false
				phantom = false
				pig = false
				piglin = false
				piglin_brute = false
				pillager = false
				polar_bear = false
				tnt = true
				pufferfish = false
				rabbit = false
				ravager = false
				salmon = false
				sheep = false
				shulker = false
				shulker_bullet = true
				silverfish = false
				skeleton = false
				skeleton_horse = false
				slime = false
				small_fireball = true
				snow_golem = false
				snowball = false
				spectral_arrow = false
				spider = false
				squid = false
				stray = false
				strider = false
				egg = false
				ender_pearl = false
				experience_bottle = true
				potion = true
				trident = false
				trader_llama = false
				tropical_fish = false
				turtle = false
				vex = true
				villager = false
				vindicator = false
				wandering_trader = false
				witch = false
				wither = true
				wither_skeleton = false
				wither_skull = true
				wolf = false
				zoglin = false
				zombie = false
				zombie_horse = false
				zombie_villager = false
				zombified_piglin = false
				player = true
				fishing_bobber = false

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true
				naga = false
				flying_pig = false
				jungle_skeleton = false
				skull = true
				chair = false
				naga_projectile = false

			[light_sources.settings.entities.additionaladditions]
				glow_stick = true

			[light_sources.settings.entities.adorn]
				seat = false

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				end_slime = true
				end_fish = true
				shadow_walker = true
				cubozoa = true
				silk_moth = true

			[light_sources.settings.entities.bewitchment]
				juniper_broom = true
				cypress_broom = true
				elder_broom = true
				dragons_blood_broom = true
				silver_arrow = true
				horned_spear = true
				owl = false
				raven = false
				snake = false
				toad = true
				ghost = true
				vampire = true
				werewolf = true
				hellhound = true
				demon = true
				leonard = true
				baphomet = true
				lilith = true
				herne = true

			[light_sources.settings.entities.botania]
				mana_burst = true
				pixie = true
				flame_ring = true
				vine_ball = true
				doppleganger = true
				magic_landmine = true
				spark = true
				thrown_item = true
				magic_missile = true
				thorn_chakram = true
				corporea_spark = true
				ender_air_bottle = true
				pool_minecart = true
				pink_wither = true
				player_mover = true
				mana_storm = true
				babylon_weapon = true
				falling_star = true
				ender_air = true

			[light_sources.settings.entities.computercraft]
				turtle_player = false

			[light_sources.settings.entities.drg_flares]
				drg_flare = true

			[light_sources.settings.entities.edenring]
				diskwing = true
				lightning_ray = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				acolyte = true
				ghoul = true
				reaper = true
				revenant = true
				nightmare = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.hookshot]
				hookshot = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.origins]
				enderian_pearl = false

			[light_sources.settings.entities.oxidized]
				copper_golem = true

			[light_sources.settings.entities.pigeons]
				pigeon = true

			[light_sources.settings.entities.redbits]
				emitter_minecart = true

			[light_sources.settings.entities.terraform]
				boat = false

			[light_sources.settings.entities.conjuring]
				soul_projectile = true
				soul_feller = true
				soul_digger = true
				soul_magnet = true
				soul_harvester = true

			[light_sources.settings.entities.moborigins]
				origin_slime = false

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				furnace = true
				chest = false
				trapped_chest = true
				ender_chest = true
				jukebox = true
				dispenser = false
				dropper = false
				sign = true
				mob_spawner = true
				piston = false
				brewing_stand = true
				enchanting_table = true
				end_portal = true
				beacon = true
				skull = false
				daylight_detector = true
				hopper = false
				comparator = true
				banner = true
				structure_block = false
				end_gateway = true
				command_block = false
				shulker_box = false
				bed = false
				conduit = true
				barrel = false
				smoker = true
				blast_furnace = true
				lectern = false
				bell = false
				jigsaw = false
				campfire = true
				beehive = true
				sculk_sensor = true

			[light_sources.settings.block_entities.adorn]
				shelf = false
				drawer = false
				kitchen_cupboard = false
				trading_station = false
				brewer = true

			[light_sources.settings.block_entities.animal_feeding_trough]
				feeding_trough = false

			[light_sources.settings.block_entities.automated_crafting]
				auto_crafter_entity = false

			[light_sources.settings.block_entities.bclib]
				chest = true
				barrel = true
				sign = true
				furnace = true

			[light_sources.settings.block_entities.betterend]
				end_stone_smelter = true
				pedestal = true
				eternal_pedestal = true
				infusion_pedestal = true
				hydrother_malvent = true

			[light_sources.settings.block_entities.betternether]
				forge = true
				furnace = true
				chest_of_drawers = true
				nether_brewing_stand = true

			[light_sources.settings.block_entities.bewitchment]
				bw_chest = true
				witch_altar = true
				witch_cauldron = true
				glyph = true
				brazier = true
				taglock_holder = true
				lockable = true
				sigil = true
				poppet_shelf = true
				juniper_chest = true
				elder_chest = true
				dragons_blood_chest = true

			[light_sources.settings.block_entities.bitsandchisels]
				bits_block_entity = true

			[light_sources.settings.block_entities.botania]
				altar = true
				mana_spreader = true
				mana_pool = true
				runic_altar = true
				mana_pylon = true
				mana_distributor = true
				mana_void = true
				enchanter = true
				turntable = true
				tiny_planet_block = true
				open_crate = true
				crafty_crate = true
				forest_eye = true
				platform = true
				alfheim_portal = true
				bifrost = true
				mini_island = true
				tiny_potato = true
				spawner_claw = true
				ender_eye_block = true
				starfield = true
				mana_fluxfield = true
				brewery = true
				terra_plate = true
				red_string_container = true
				red_string_dispenser = true
				red_string_fertilizer = true
				red_string_comparator = true
				red_string_relay = true
				mana_flame = true
				prism = true
				corporea_index = true
				corporea_funnel = true
				pump = true
				fake_air = true
				corporea_interceptor = true
				corporea_crystal_cube = true
				incense_plate = true
				hourglass = true
				spark_changer = true
				cocoon = true
				light_relay = true
				cacophonium_block = true
				bellows = true
				cell_block = true
				red_string_interceptor = true
				gaia_head = true
				corporea_retainer = true
				teru_teru_bozu = true
				avatar = true
				animated_torch = true
				pure_daisy = true
				manastar = true
				hydroangeas = true
				endoflame = true
				thermalily = true
				rosa_arcana = true
				munchdew = true
				entropinnyum = true
				kekimurus = true
				gourmaryllis = true
				narslimmus = true
				spectrolus = true
				dandelifeon = true
				rafflowsia = true
				shulk_me_not = true
				bellethorn = true
				bellethorn_chibi = true
				bergamute = true
				dreadthorn = true
				heisei_dream = true
				tigerseye = true
				jaded_amaranthus = true
				orechid = true
				fallen_kanade = true
				exoflame = true
				agricarnation = true
				agricarnation_chibi = true
				hopperhock = true
				hopperhock_chibi = true
				tangleberrie = true
				tangleberrie_chibi = true
				jiyuulia = true
				jiyuulia_chibi = true
				rannuncarpus = true
				rannuncarpus_chibi = true
				hyacidus = true
				pollidisiac = true
				clayconia = true
				clayconia_chibi = true
				loonium = true
				daffomill = true
				vinculotus = true
				spectranthemum = true
				medumone = true
				marimorphosis = true
				marimorphosis_chibi = true
				bubbell = true
				bubbell_chibi = true
				solegnolia = true
				solegnolia_chibi = true
				orechid_ignem = true
				labellia = true

			[light_sources.settings.block_entities.comforts]
				sleeping_bag = true
				hammock = true

			[light_sources.settings.block_entities.computercraft]
				monitor_normal = true
				monitor_advanced = true
				computer_normal = true
				computer_advanced = true
				computer_command = true
				turtle_normal = true
				turtle_advanced = true
				speaker = true
				disk_drive = true
				printer = true
				wired_modem_full = true
				cable = true
				wireless_modem_normal = true
				wireless_modem_advanced = true

			[light_sources.settings.block_entities.conjuring]
				conjurer = true
				soulfire_forge = true
				blackstone_pedestal = true
				soul_funnel = true
				soul_weaver = true
				gem_tinkerer = true

			[light_sources.settings.block_entities.drg_flares]
				flare_light_block_entity = true

			[light_sources.settings.block_entities.edenring]
				eden_portal = true

			[light_sources.settings.block_entities.gofish]
				astral_crate = true

			[light_sources.settings.block_entities.graveyard]
				gravestone_block_entity = true
				urn_block_entity = true
				sarcophagus_block_entity = true
				brazier_block_entity = true

			[light_sources.settings.block_entities.ironchests]
				copper_chest = true
				iron_chest = true
				gold_chest = true
				diamond_chest = true
				emerald_chest = true
				crystal_chest = true
				obsidian_chest = true
				christmas_chest = true

			[light_sources.settings.block_entities.netherchest]
				nether_chest = true

			[light_sources.settings.block_entities.oxidized]
				copper_kiln_block_entity = true

			[light_sources.settings.block_entities.pipe]
				item_pipe = true

			[light_sources.settings.block_entities.redstonebits]
				placer = true
				breaker = true
				checker = true
				redstone_gate = true

			[light_sources.settings.block_entities.small_artifacts]
				copper_altar_entity = true

			[light_sources.settings.block_entities.the_extractinator]
				extractinator_entity = true

			[light_sources.settings.block_entities.toms_storage]

				[light_sources.settings.block_entities.toms_storage.ts]

					[light_sources.settings.block_entities.toms_storage.ts.inventory_connector]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.storage_terminal]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.open_crate]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.painted]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.inventory_cable_connector]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.inventory_cable_connector_filtered]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.inventory_proxy]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.crafting_terminal]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.inventoty_hopper_basic]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.level_emitter]
						tile = true

			[light_sources.settings.block_entities.waystones]
				waystone = true
				sharestone = true
				warp_plate = true
				portstone = true

