name = "Actually Unbreaking [Fabric]"
filename = "actuallyunbreaking-1.18.1-0.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3665/458/actuallyunbreaking-1.18.1-0.3.0.jar"
hash-format = "sha1"
hash = "9e363d0e09524d40b5cf01d9249fe8035f110c2c"

[update]
[update.curseforge]
file-id = 3665458
project-id = 442960
