name = "Alternate Current"
filename = "alternate-current-mc1.18-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/113/alternate-current-mc1.18-1.1.0.jar"
hash-format = "sha1"
hash = "d6b1036e76c82186c3925c4258f4d7d1ee873de8"

[update]
[update.curseforge]
file-id = 3542113
project-id = 548115
