name = "Animal Feeding Trough [Fabric | Forge]"
filename = "animal_feeding_trough-1.0.3+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/552/animal_feeding_trough-1.0.3+1.18.1.jar"
hash-format = "sha1"
hash = "37fbc32015e29a8204dff1ced1aa4034eb87b67d"

[update]
[update.curseforge]
file-id = 3580552
project-id = 445838
