name = "Artifacts (Fabric)"
filename = "artifacts-6.0.0+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3656/320/artifacts-6.0.0+fabric.jar"
hash-format = "sha1"
hash = "b177973bc58f8ba4838c321a98822aedd5bcb001"

[update]
[update.curseforge]
file-id = 3656320
project-id = 401236
