name = "Basic AIOTs"
filename = "basicaiots-1.3.3+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/523/basicaiots-1.3.3+1.18.1.jar"
hash-format = "sha1"
hash = "881448682e5691a17b034a4a93b8563b96e1447f"

[update]
[update.curseforge]
file-id = 3575523
project-id = 476080
