name = "BCLib"
filename = "bclib-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3650/880/bclib-1.3.4.jar"
hash-format = "sha1"
hash = "61fb21dafb2e33006d7722f14f18b92ba3a63e7f"

[update]
[update.curseforge]
file-id = 3650880
project-id = 495191
