name = "Beacon Overhaul"
filename = "BeaconOverhaul-1.5.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3561/472/BeaconOverhaul-1.5.0+1.18.jar"
hash-format = "sha1"
hash = "abbab18c6411bbdf52ab3990876ce7778f75f3ee"

[update]
[update.curseforge]
file-id = 3561472
project-id = 430382
