name = "Beenfo"
filename = "beenfo-1.18.1-fabric0.45.0-1.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3585/804/beenfo-1.18.1-fabric0.45.0-1.3.3.jar"
hash-format = "sha1"
hash = "eb4786cc26d3a35c7369b32a23ecf7cd35e7f5df"

[update]
[update.curseforge]
file-id = 3585804
project-id = 357256
