name = "Better Controls"
filename = "BetterControls-Fabric-1.18+v1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3565/372/BetterControls-Fabric-1.18+v1.2.3.jar"
hash-format = "sha1"
hash = "98e117aadb9746c7ca4f46dee7f3ff519f32be90"

[update]
[update.curseforge]
file-id = 3565372
project-id = 413259
