name = "Better Than Mending"
filename = "betterthanmending-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3213/798/betterthanmending-1.3.0.jar"
hash-format = "sha1"
hash = "4e1b2c8baad90324d7b45eaa4c39f8249c3d0a64"

[update]
[update.curseforge]
file-id = 3213798
project-id = 264738
