name = "Better Ping Display [Fabric]"
filename = "BetterPingDisplay-Fabric-1.18.1-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3565/287/BetterPingDisplay-Fabric-1.18.1-1.1.1.jar"
hash-format = "sha1"
hash = "baa7a5a1cabdcda36e6819b5cff6e44a86fce708"

[update]
[update.curseforge]
file-id = 3565287
project-id = 406343
