name = "Bewitchment"
filename = "bewitchment-1.18-15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/524/bewitchment-1.18-15.jar"
hash-format = "sha1"
hash = "48044b31a67a97cc49859d512dda73c4cce8e4db"

[update]
[update.curseforge]
file-id = 3672524
project-id = 394915
