name = "Bobby"
filename = "bobby-3.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3566/756/bobby-3.1.0.jar"
hash-format = "sha1"
hash = "380e4a7aa7c746db8bd908991823c9f38b5569a4"

[update]
[update.curseforge]
file-id = 3566756
project-id = 409301
