name = "Camera Utils"
filename = "camerautils-1.18.1-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3557/166/camerautils-1.18.1-1.0.0.jar"
hash-format = "sha1"
hash = "4ecee25b38b809f9363e0fc2d6f31c1237e5ff82"

[update]
[update.curseforge]
file-id = 3557166
project-id = 510234
