name = "Carpet"
filename = "fabric-carpet-1.18.1-1.4.57+v220119.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/878/fabric-carpet-1.18.1-1.4.57+v220119.jar"
hash-format = "sha1"
hash = "4e6bcf231b53147bd8b32784090e3e615063b8b1"

[update]
[update.curseforge]
file-id = 3613878
project-id = 349239
