name = "CC: Restitched"
filename = "cc-restitched-1.100.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/494/cc-restitched-1.100.2.jar"
hash-format = "sha1"
hash = "181641512569e8ccafa7cc46d4ef9394a77938f2"

[update]
[update.curseforge]
file-id = 3669494
project-id = 462672
