name = "Chat Coords"
filename = "chat-coords-0.2.2152.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/934/chat-coords-0.2.2152.jar"
hash-format = "sha1"
hash = "e1a2358068b646c77ea9ed35ba3c48644c26ceff"

[update]
[update.curseforge]
file-id = 3590934
project-id = 554855
