name = "Clear Skies"
filename = "clear-skies-fabric-mc118-2.0.88.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3565/213/clear-skies-fabric-mc118-2.0.88.jar"
hash-format = "sha1"
hash = "0d8a4bab50392d83f57f3bf0dfb7b2c8fc13790d"

[update]
[update.curseforge]
file-id = 3565213
project-id = 332523
