name = "Collective (Fabric)"
filename = "collective-fabric-1.18.x-4.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3678/695/collective-fabric-1.18.x-4.9.jar"
hash-format = "sha1"
hash = "7136f36f3323a85f1a8dfb885ee28e1e1acece47"

[update]
[update.curseforge]
file-id = 3678695
project-id = 526606
