name = "Conjuring [Fabric/Forge]"
filename = "conjuring-1.0.20+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/193/conjuring-1.0.20+1.18.jar"
hash-format = "sha1"
hash = "88242305fdfcad1fc7cb645509c1498b68a78c51"

[update]
[update.curseforge]
file-id = 3615193
project-id = 422310
