name = "Crawl (Fabric)"
filename = "crawl-0.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3621/981/crawl-0.10.2.jar"
hash-format = "sha1"
hash = "dee81b1e310277524edfe59e6e2d6eee5bb9f21a"

[update]
[update.curseforge]
file-id = 3621981
project-id = 314579
