name = "Enchanted ToolTips"
filename = "EnchantedToolTips-1.3.5-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/179/EnchantedToolTips-1.3.5-1.18.jar"
hash-format = "sha1"
hash = "687d29ef9d370c4bdef2a0faaba5d4002bec672b"

[update]
[update.curseforge]
file-id = 3554179
project-id = 331965
