name = "Enhanced Celestials(Fabric) - Blood Moons & Harvest Moons"
filename = "enhancedcelestials-1.18-2.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/569/enhancedcelestials-1.18-2.0.6.jar"
hash-format = "sha1"
hash = "5c1576db9821c4db4e5a0b7bfa3e52a8c1dd1b2d"

[update]
[update.curseforge]
file-id = 3542569
project-id = 443694
