name = "Entity Texture Features - [Fabric]"
filename = "entity-texture-features-1.18.1-2.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/839/entity-texture-features-1.18.1-2.4.1.jar"
hash-format = "sha1"
hash = "77e6efe0600ee40233937380acc9da9c65641af5"

[update]
[update.curseforge]
file-id = 3681839
project-id = 568563
