name = "Entity Texture Features - [Fabric]"
filename = "entity-texture-features_1_18_1-2.3.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/318/entity-texture-features_1_18_1-2.3.6.jar"
hash-format = "sha1"
hash = "4bcfbdec7b70aefbd092bb15976ff2fe1adf2de5"

[update]
[update.curseforge]
file-id = 3680318
project-id = 568563
