name = "Extra Classes - Origins"
filename = "extra_classes_origins.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3659/789/extra_classes_origins.jar"
hash-format = "sha1"
hash = "984e4506b1a52c756abcffad37da06070c23947c"

[update]
[update.curseforge]
file-id = 3659789
project-id = 565536
