name = "FabricSkyboxes"
filename = "fabricskyboxes-1.18-0.5.4.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YBz7DOs8/versions/0.5.4/fabricskyboxes-1.18-0.5.4.jar"
hash-format = "sha1"
hash = "7f91fff09c1886c8640cdeedefef35169a59c8dc"

[update]
[update.modrinth]
mod-id = "YBz7DOs8"
version = "TXjtXxm7"
