name = "Freecam (Fabric)"
filename = "freecam-0.4.8+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/589/freecam-0.4.8+1.18.jar"
hash-format = "sha1"
hash = "27598a2b8c5d8092a6e4e8e8089bbddeb3c00e06"

[update]
[update.curseforge]
file-id = 3670589
project-id = 557076
