name = "Giselbaer's Durability Viewer"
filename = "durabilityviewer-1.18-fabric0.43.1-1.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/427/durabilityviewer-1.18-fabric0.43.1-1.10.2.jar"
hash-format = "sha1"
hash = "65d508c8a979c4ad047aee1a2b33ca716057a42e"

[update]
[update.curseforge]
file-id = 3543427
project-id = 262146
