name = "HealthCare"
filename = "healthcare-1.0.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/311/healthcare-1.0.11.jar"
hash-format = "sha1"
hash = "4173acbf86533527a022bbfa5a3697e16046b5b4"

[update]
[update.curseforge]
file-id = 3649311
project-id = 466750
