name = "Imperishable Items (Fabric)"
filename = "imperishable-items-fabric-mc1.18.1-2.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3574/0/imperishable-items-fabric-mc1.18.1-2.1.1.jar"
hash-format = "sha1"
hash = "0a111116b9309392fb7bb805d80c17130780b9aa"

[update]
[update.curseforge]
file-id = 3574000
project-id = 538649
