name = "Incantationem"
filename = "incantationem-1.1.3+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3571/914/incantationem-1.1.3+1.18.1.jar"
hash-format = "sha1"
hash = "ddab3d526aba4fac0de08cec780af9e7c0caa1c9"

[update]
[update.curseforge]
file-id = 3571914
project-id = 483166
