name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3679/957/InventoryProfilesNext-fabric-1.18-1.3.5.jar"
hash-format = "sha1"
hash = "4745204a002992184cad090ca9345f719b58085c"

[update]
[update.curseforge]
file-id = 3679957
project-id = 495267
