name = "LambdaBetterGrass"
filename = "lambdabettergrass-1.2.2+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3584/355/lambdabettergrass-1.2.2+1.17.jar"
hash-format = "sha1"
hash = "7fef2f1d2c610b9d49721f3e297206c18f9dd0d0"

[update]
[update.curseforge]
file-id = 3584355
project-id = 400322
