name = "Lovely Snails"
filename = "lovely_snails-1.0.3+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/566/lovely_snails-1.0.3+1.18.jar"
hash-format = "sha1"
hash = "e1386ff707b60a09a6e86b6425efc0ae636a943a"

[update]
[update.curseforge]
file-id = 3546566
project-id = 499425
