name = "Mo' Structures (Fabric)"
filename = "mostructures-1.3.0-pre1-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3567/77/mostructures-1.3.0-pre1-1.18.jar"
hash-format = "sha1"
hash = "f2ddbdc4ccb5f4f726876fbaf5b5849d9a45ffc0"

[update]
[update.curseforge]
file-id = 3567077
project-id = 378266
