name = "Mob Origins"
filename = "moborigins-1.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/968/moborigins-1.8.0.jar"
hash-format = "sha1"
hash = "5fea853b48bbe70e4439ae35ecaee4f06e1c5534"

[update]
[update.curseforge]
file-id = 3542968
project-id = 449974
