name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.8.3+mc1.18-pre5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3657/755/mousewheelie-1.8.3+mc1.18-pre5.jar"
hash-format = "sha1"
hash = "b64f90a7392aa45ffd5272bcae98a3f6ba3a8d63"

[update]
[update.curseforge]
file-id = 3657755
project-id = 317514
