name = "No Telemetry"
filename = "no-telemetry-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/361/no-telemetry-1.3.0.jar"
hash-format = "sha1"
hash = "0aa4244d3f97006cb4bacbdefbd9ea41e17f1400"

[update]
[update.curseforge]
file-id = 3549361
project-id = 530816
