name = "NoCubes"
filename = "NoCubes-1.18.1-0.5.0-dev-fe6e9dea.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3607/990/NoCubes-1.18.1-0.5.0-dev-fe6e9dea.jar"
hash-format = "sha1"
hash = "cd187ee482eaa8932dc05f76af58007a7d182a63"

[update]
[update.curseforge]
file-id = 3607990
project-id = 309664
