name = "Notes Fabric"
filename = "notes-1.18-1.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3602/385/notes-1.18-1.0.10.jar"
hash-format = "sha1"
hash = "38357d698e4e62cdb95df83257840fac1e54db40"

[update]
[update.curseforge]
file-id = 3602385
project-id = 388252
