name = "⚒️ On A Stick [FABRIC]"
filename = "onastick-fabric-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/716/onastick-fabric-2.0.0.jar"
hash-format = "sha1"
hash = "66f8993e727683fd3e4da057e87da1d159e15e0d"

[update]
[update.curseforge]
file-id = 3590716
project-id = 550544
