name = "Origins: Classes"
filename = "Origins-Classes-1.18-1.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/925/Origins-Classes-1.18-1.2.4.jar"
hash-format = "sha1"
hash = "42222b4b60c335d005c710a589a86289d5ac1cb7"

[update]
[update.curseforge]
file-id = 3554925
project-id = 401833
