name = "Origins: Umbrellas"
filename = "originsumbrellas-1.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/971/originsumbrellas-1.5.1.jar"
hash-format = "sha1"
hash = "a64509888d20fa6af3da9986873feca4fbdfe6d3"

[update]
[update.curseforge]
file-id = 3670971
project-id = 453378
