name = "oÏ‰o (owo-lib)"
filename = "owo-lib-0.5.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/495/owo-lib-0.5.2+1.18.jar"
hash-format = "sha1"
hash = "b8d0a93e93f5d627625ebf020402552828e6f344"

[update]
[update.curseforge]
file-id = 3646495
project-id = 532610
