name = "Presence Footsteps"
filename = "PresenceFootsteps-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3551/598/PresenceFootsteps-1.4.0.jar"
hash-format = "sha1"
hash = "9de4458abefaaebfdeadde8b1216f9a939a9fc87"

[update]
[update.curseforge]
file-id = 3551598
project-id = 334259
