name = "Puzzle"
filename = "puzzle-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/769/puzzle-1.1.0.jar"
hash-format = "sha1"
hash = "56365b0e1e27288c45ec680be7d41cff8d389015"

[update]
[update.curseforge]
file-id = 3599769
project-id = 563977
