name = "Reasonable Sorting"
filename = "reasonable-sorting-1.3-mc1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/162/reasonable-sorting-1.3-mc1.18.jar"
hash-format = "sha1"
hash = "4c638581ff4b4dd71dfb82a678bd0448c0acfc23"

[update]
[update.curseforge]
file-id = 3604162
project-id = 520169
