name = "Reasonable Sorting"
filename = "reasonable-sorting-1.5-mc1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/139/reasonable-sorting-1.5-mc1.18.jar"
hash-format = "sha1"
hash = "84feb051847666c95763d4e0e242a92d7d841308"

[update]
[update.curseforge]
file-id = 3680139
project-id = 520169
