name = "Simple Backpack [FABRIC]"
filename = "SimpleBackpack_Fabric-1.18.1-1.2.31.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/360/SimpleBackpack_Fabric-1.18.1-1.2.31.jar"
hash-format = "sha1"
hash = "0a2afafb98370b73dbc757bf19f70868d412b087"

[update]
[update.curseforge]
file-id = 3666360
project-id = 383999
