name = "Skin Layers 3D (Fabric/Forge)"
filename = "3dskinlayers-fabric-1.4.2-mc1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/241/3dskinlayers-fabric-1.4.2-mc1.18.2.jar"
hash-format = "sha1"
hash = "56216715e65b9535ec5338cf5ed4d954e9a80dd9"

[update]
[update.curseforge]
file-id = 3672241
project-id = 521480
