name = "Sky Villages [Fabric]"
filename = "SkyVillages-1.0.1-1.18.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/441/SkyVillages-1.0.1-1.18.1-fabric.jar"
hash-format = "sha1"
hash = "940f93a0bf09248c0c7c7c825cd058434df16501"

[update]
[update.curseforge]
file-id = 3587441
project-id = 545483
