name = "SlimyFloor"
filename = "slimyfloor-1.18-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/951/slimyfloor-1.18-1.2.2.jar"
hash-format = "sha1"
hash = "575e2132b6e186061878a2a3256e6d2f5441c407"

[update]
[update.curseforge]
file-id = 3554951
project-id = 456996
