name = "Small Artifacts"
filename = "small_artifacts-0.1.0-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3562/475/small_artifacts-0.1.0-1.18.jar"
hash-format = "sha1"
hash = "0c804bac415c18d764c811a2dca202d474946227"

[update]
[update.curseforge]
file-id = 3562475
project-id = 528262
