name = "Smooth Boot (Fabric)"
filename = "smoothboot-fabric-1.18-1.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/723/smoothboot-fabric-1.18-1.7.0.jar"
hash-format = "sha1"
hash = "b9747389234b3bc4fa04d7d5b4c05e606e2d1abe"

[update]
[update.curseforge]
file-id = 3549723
project-id = 415758
