name = "Spyglass Improvements: Zoom, Quick Access... [Fabric/Forge]"
filename = "spyglass-improvements-1.1+mc1.18.1+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3645/220/spyglass-improvements-1.1+mc1.18.1+fabric.jar"
hash-format = "sha1"
hash = "0e7793e7cd4dbc7ec31d2b3ad3cc419a0a510b50"

[update]
[update.curseforge]
file-id = 3645220
project-id = 571264
