name = "Subterrestrial (Fabric)"
filename = "Subterrestrial-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/704/Subterrestrial-1.0.1.jar"
hash-format = "sha1"
hash = "c61a6c70d525aabccf10a7833101c6fb7dacf9e4"

[update]
[update.curseforge]
file-id = 3654704
project-id = 575588
