name = "TabTPS"
filename = "tabtps-fabric-mc1.18-1.3.11.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/cUhi3iB2/versions/1.3.11/tabtps-fabric-mc1.18-1.3.11.jar"
hash-format = "sha1"
hash = "8cb6382f3b654e79c7b731edf3c92b5f5784a127"

[update]
[update.modrinth]
mod-id = "cUhi3iB2"
version = "L48r3Mn5"
