name = "Tax Free Levels (Fabric/Forge)"
filename = "TaxFreeLevels-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3553/880/TaxFreeLevels-1.3.jar"
hash-format = "sha1"
hash = "30272892efdcb149e1845d5890f7ebd20544ec24"

[update]
[update.curseforge]
file-id = 3553880
project-id = 462128
