name = "Terralith 2.0 ~ Overworld Evolved"
filename = "Terralith_v2.0.12_Fabric+Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/78/Terralith_v2.0.12_Fabric+Forge.jar"
hash-format = "sha1"
hash = "640f9a19bca8b663179c015dec433a1797b3452a"

[update]
[update.curseforge]
file-id = 3606078
project-id = 513688
