name = "The Graveyard (FABRIC)"
filename = "The_Graveyard_1.6_(FABRIC)_for_1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3665/490/The_Graveyard_1.6_(FABRIC)_for_1.18.1.jar"
hash-format = "sha1"
hash = "9c861dfe17a76f9ad449a6584d15d21514930df1"

[update]
[update.curseforge]
file-id = 3665490
project-id = 514468
