name = "Villagers follow Emeralds [Fabric]"
filename = "villagers-follow-emeralds-1.2.0 1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/451/villagers-follow-emeralds-1.2.0%201.18.jar"
hash-format = "sha1"
hash = "f5fdce2c25f5835be3d2232ffe6dedfb9b103f6c"

[update]
[update.curseforge]
file-id = 3541451
project-id = 391911
