name = "Waystones (Fabric Edition)"
filename = "waystones-fabric-1.18.1-9.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3658/45/waystones-fabric-1.18.1-9.0.4.jar"
hash-format = "sha1"
hash = "90b535219a35bb777a729caab09db97edcb0009f"

[update]
[update.curseforge]
file-id = 3658045
project-id = 500087
