name = "Where Is It"
filename = "whereisit-1.18.1-1.14.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3602/648/whereisit-1.18.1-1.14.7.jar"
hash-format = "sha1"
hash = "58bb2258842337050aa0f43bfd8b1e343002c5c5"

[update]
[update.curseforge]
file-id = 3602648
project-id = 378036
