name = "Wolves With Armor"
filename = "wolves-with-armor-1.7.0-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/382/wolves-with-armor-1.7.0-1.18.jar"
hash-format = "sha1"
hash = "467ea703756134f18a8d3adc355ea691136139fb"

[update]
[update.curseforge]
file-id = 3554382
project-id = 375969
