name = "Zombify"
filename = "zombify-0.1.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/DTmZ5lnu/versions/0.1.0/zombify-0.1.0.jar"
hash-format = "sha1"
hash = "3ac8de3a372a42b8b23afb8cbba3980aec65ffbd"

[update]
[update.modrinth]
mod-id = "DTmZ5lnu"
version = "VXnkKV2R"
