name = "Zoomify"
filename = "Zoomify-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/317/Zoomify-1.1.0.jar"
hash-format = "sha1"
hash = "effd7b04bd9a04246d12ba6a1ded6e53aa3d70bf"

[update]
[update.curseforge]
file-id = 3630317
project-id = 574741
